name: CI

on:
  push:
    branches: [ "main", "nova-feature" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Teste simples
        run: echo "CI funcionando!"